# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-master-test',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/nbdev-master-test',
                'lib_path': 'nbdev_master_test'},
  'syms': {'nbdev_master_test.core': {'nbdev_master_test.core.foo': ('core.html#foo', 'nbdev_master_test/core.py')}}}